# Generated by Django 4.0.6 on 2022-09-05 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='transcripted_Sentence_slice',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
